//! Expanded provider catalog for `omgb provider add <id>`.
//!
//! Contains 100+ OpenAI-compatible cloud endpoints, local model servers, and
//! common OpenCode-style endpoint templates.

use super::{ProviderConfig, provider_env_keys};

const fn t(
    id: &'static str,
    name: &'static str,
    model: &'static str,
    base_url: &'static str,
    env_key: Option<&'static str>,
    context_window: u64,
) -> ProviderTemplate {
    ProviderTemplate {
        id,
        name,
        model,
        base_url,
        env_key,
        extra_headers: None,
        context_window: Some(context_window),
        api_backend: Some("chat_completions"),
    }
}

#[derive(Debug, Clone)]
pub struct ProviderTemplate {
    pub id: &'static str,
    pub name: &'static str,
    pub model: &'static str,
    pub base_url: &'static str,
    pub env_key: Option<&'static str>,
    pub extra_headers: Option<&'static [(&'static str, &'static str)]>,
    pub context_window: Option<u64>,
    pub api_backend: Option<&'static str>,
}

impl ProviderTemplate {
    pub fn to_provider_config(&self) -> ProviderConfig {
        ProviderConfig {
            id: self.id.into(),
            name: self.name.into(),
            model: self.model.into(),
            base_url: self.base_url.into(),
            api_backend: self.api_backend.map(|s| s.into()),
            env_key: provider_env_keys(self.id, self.env_key),
            extra_headers: self.extra_headers.map(|h| {
                h.iter()
                    .map(|(k, v)| (k.to_string(), v.to_string()))
                    .collect::<std::collections::HashMap<_, _>>()
            }),
            context_window: self.context_window,
            auto_compact_threshold_percent: Some(80),
            temperature: None,
            top_p: None,
            max_completion_tokens: None,
        }
    }
}

pub fn provider_template(id: &str) -> Option<ProviderConfig> {
    TEMPLATES
        .iter()
        .find(|t| t.id == id)
        .map(|t| t.to_provider_config())
}

pub(crate) const TEMPLATES: &[ProviderTemplate] = &[
    // OpenAI-compatible cloud endpoints
    t(
        "groq",
        "Groq",
        "llama-3.3-70b-versatile",
        "https://api.groq.com/openai/v1",
        Some("GROQ_API_KEY"),
        128_000,
    ),
    t(
        "mistral",
        "Mistral",
        "mistral-large-latest",
        "https://api.mistral.ai/v1",
        Some("MISTRAL_API_KEY"),
        128_000,
    ),
    t(
        "cohere",
        "Cohere",
        "command-a-plus-05-2026",
        "https://api.cohere.ai/compatibility/v1",
        Some("COHERE_API_KEY"),
        128_000,
    ),
    t(
        "together",
        "Together AI",
        "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        "https://api.together.xyz/v1",
        Some("TOGETHER_API_KEY"),
        128_000,
    ),
    t(
        "fireworks",
        "Fireworks AI",
        "accounts/fireworks/models/llama-v3p1-70b-instruct",
        "https://api.fireworks.ai/inference/v1",
        Some("FIREWORKS_API_KEY"),
        128_000,
    ),
    t(
        "perplexity",
        "Perplexity",
        "sonar",
        "https://api.perplexity.ai",
        Some("PERPLEXITY_API_KEY"),
        128_000,
    ),
    t(
        "deepseek",
        "DeepSeek",
        "deepseek-chat",
        "https://api.deepseek.com/v1",
        Some("DEEPSEEK_API_KEY"),
        128_000,
    ),
    t(
        "ai21",
        "AI21",
        "jamba-1.5-mini",
        "https://api.ai21.com/studio/v1",
        Some("AI21_API_KEY"),
        256_000,
    ),
    t(
        "gemini",
        "Gemini",
        "gemini-1.5-flash",
        "https://generativelanguage.googleapis.com/v1beta/openai",
        Some("GEMINI_API_KEY"),
        128_000,
    ),
    t(
        "anyscale",
        "Anyscale",
        "meta-llama/Llama-2-70b-chat-hf",
        "https://api.endpoints.anyscale.com/v1",
        Some("ANYSCALE_API_KEY"),
        4_096,
    ),
    t(
        "cerebras",
        "Cerebras",
        "llama3.1-70b",
        "https://api.cerebras.net/v1",
        Some("CEREBRAS_API_KEY"),
        128_000,
    ),
    t(
        "friendli",
        "FriendliAI",
        "meta-llama-3.1-70b-instruct",
        "https://api.friendli.ai/v1",
        Some("FRIENDLI_API_KEY"),
        128_000,
    ),
    t(
        "hyperbolic",
        "Hyperbolic",
        "meta-llama/Meta-Llama-3.1-70B-Instruct",
        "https://api.hyperbolic.xyz/v1",
        Some("HYPERBOLIC_API_KEY"),
        8_192,
    ),
    t(
        "lamini",
        "Lamini",
        "Llama-3.1-8B-Instruct",
        "https://api.lamini.ai/v1",
        Some("LAMINI_API_KEY"),
        8_192,
    ),
    t(
        "monster",
        "Monster API",
        "meta-llama/Meta-Llama-3.1-8B-Instruct",
        "https://llm.monsterapi.ai/v1",
        Some("MONSTER_API_KEY"),
        128_000,
    ),
    t(
        "novita",
        "Novita",
        "deepseek/deepseek-chat",
        "https://api.novita.ai/openai",
        Some("NOVITA_API_KEY"),
        128_000,
    ),
    t(
        "octoai",
        "OctoAI",
        "meta-llama-3-70b-instruct",
        "https://text.octoai.run/v1",
        Some("OCTOAI_API_KEY"),
        128_000,
    ),
    t(
        "upstage",
        "Upstage",
        "solar-pro",
        "https://api.upstage.ai/v1",
        Some("UPSTAGE_API_KEY"),
        32_768,
    ),
    t(
        "zhipu",
        "Zhipu AI",
        "glm-4",
        "https://open.bigmodel.cn/api/paas/v4",
        Some("ZHIPU_API_KEY"),
        128_000,
    ),
    t(
        "moonshot",
        "Moonshot",
        "moonshot-v1-8k",
        "https://api.moonshot.cn/v1",
        Some("MOONSHOT_API_KEY"),
        8_192,
    ),
    t(
        "qwen",
        "Qwen",
        "qwen-plus",
        "https://dashscope.aliyuncs.com/compatible-mode/v1",
        Some("QWEN_API_KEY"),
        128_000,
    ),
    t(
        "yi",
        "01.AI",
        "yi-large",
        "https://api.01.ai/v1",
        Some("YI_API_KEY"),
        16_384,
    ),
    t(
        "lingyi",
        "Lingyi Wanwu",
        "abab6.5-chat",
        "https://api.lingyiwanwu.com/v1",
        Some("LINGYI_API_KEY"),
        8_192,
    ),
    t(
        "minimax",
        "MiniMax",
        "abab5.5-chat",
        "https://api.minimaxi.chat/v1",
        Some("MINIMAX_API_KEY"),
        8_192,
    ),
    t(
        "baichuan",
        "Baichuan",
        "Baichuan4",
        "https://api.baichuan-ai.com/v1",
        Some("BAICHUAN_API_KEY"),
        128_000,
    ),
    t(
        "spark",
        "Spark",
        "generalv3.5",
        "https://spark-api-open.xf-yun.com/v1",
        Some("SPARK_API_KEY"),
        8_192,
    ),
    t(
        "doubao",
        "Doubao",
        "doubao-pro-32k",
        "https://ark.cn-beijing.volces.com/api/v3",
        Some("DOUBAO_API_KEY"),
        32_768,
    ),
    t(
        "hunyuan",
        "Hunyuan",
        "hunyuan-pro",
        "https://hunyuan-api.tencent.com/v1",
        Some("HUNYUAN_API_KEY"),
        32_768,
    ),
    t(
        "stepfun",
        "Stepfun",
        "step-1-8k",
        "https://api.stepfun.com/v1",
        Some("STEPFUN_API_KEY"),
        8_192,
    ),
    t(
        "internlm",
        "InternLM",
        "internlm2.5-20b",
        "https://api.intern-ai.org.cn/v1",
        Some("INTERNLM_API_KEY"),
        32_768,
    ),
    t(
        "sensenova",
        "SenseNova",
        "sensenova-6.7-flash-lite",
        "https://token.sensenova.cn/v1",
        Some("SENSENOVA_API_KEY"),
        32_768,
    ),
    t(
        "github-models",
        "GitHub Models",
        "gpt-4o",
        "https://models.inference.ai.azure.com",
        Some("GITHUB_MODELS_API_KEY"),
        128_000,
    ),
    t(
        "siliconflow",
        "SiliconFlow",
        "Qwen/Qwen2.5-72B-Instruct",
        "https://api.siliconflow.cn/v1",
        Some("SILICONFLOW_API_KEY"),
        128_000,
    ),
    t(
        "sambanova",
        "SambaNova",
        "Meta-Llama-3.1-70B-Instruct",
        "https://api.sambanova.ai/v1",
        Some("SAMBANOVA_API_KEY"),
        128_000,
    ),
    t(
        "lepton",
        "Lepton",
        "llama3-1-70b",
        "https://api.lepton.ai/v1",
        Some("LEPTON_API_KEY"),
        128_000,
    ),
    t(
        "nvidia",
        "NVIDIA NIM",
        "nvidia/llama-3.1-nemotron-70b-instruct",
        "https://integrate.api.nvidia.com/v1",
        Some("NVIDIA_API_KEY"),
        128_000,
    ),
    t(
        "deepinfra",
        "DeepInfra",
        "deepseek-ai/DeepSeek-V3",
        "https://api.deepinfra.com/v1/openai",
        Some("DEEPINFRA_API_KEY"),
        128_000,
    ),
    t(
        "aimlapi",
        "AIMLAPI",
        "gpt-4o",
        "https://api.aimlapi.com/v1",
        Some("AIMLAPI_API_KEY"),
        128_000,
    ),
    t(
        "arliai",
        "ArliAI",
        "Llama-3.3-70B-ArliAI-RPMax-v3",
        "https://api.arliai.com/v1",
        Some("ARLIAI_API_KEY"),
        128_000,
    ),
    t(
        "chutes",
        "Chutes",
        "Qwen/Qwen3-32B-TEE",
        "https://llm.chutes.ai/v1",
        Some("CHUTES_API_KEY"),
        128_000,
    ),
    t(
        "kluster",
        "Kluster",
        "meta-llama/Llama-3.1-405B-Instruct",
        "https://api.kluster.ai/v1",
        Some("KLUSTER_API_KEY"),
        128_000,
    ),
    t(
        "speka",
        "Speka",
        "meta/llama-3.3-70b-instruct",
        "https://speka.me/v1",
        Some("SPEKA_API_KEY"),
        128_000,
    ),
    t(
        "featherless",
        "Featherless",
        "Qwen/Qwen2.5-7B-Instruct",
        "https://api.featherless.ai/v1",
        Some("FEATHERLESS_API_KEY"),
        128_000,
    ),
    t(
        "aipower",
        "AIPower",
        "deepseek/deepseek-chat",
        "https://api.aipower.me/v1",
        Some("AIPOWER_API_KEY"),
        128_000,
    ),
    t(
        "huggingface",
        "Hugging Face",
        "meta-llama/Meta-Llama-3.1-8B-Instruct",
        "https://router.huggingface.co/v1",
        Some("HUGGINGFACE_API_KEY"),
        128_000,
    ),
    t(
        "sail",
        "Sail",
        "zai-org/GLM-5.2-FP8",
        "https://api.sailresearch.com/v1",
        Some("SAIL_API_KEY"),
        1_000_000,
    ),
    t(
        "textcortex",
        "TextCortex",
        "kimi-k2-5",
        "https://api.textcortex.com/v1",
        Some("TEXTCORTEX_API_KEY"),
        128_000,
    ),
    t(
        "thebai",
        "TheB.AI",
        "gpt-4o",
        "https://api.theb.ai/v1",
        Some("THEBAI_API_KEY"),
        8_192,
    ),
    t(
        "tune",
        "Tune",
        "meta/llama-3.1-8b-instruct",
        "https://proxy.tune.app",
        Some("TUNE_API_KEY"),
        128_000,
    ),
    t(
        "poe",
        "Poe",
        "gpt-4o",
        "https://api.poe.com/v1",
        Some("POE_API_KEY"),
        128_000,
    ),
    t(
        "uniterouter",
        "UniterRouter",
        "gpt-4o",
        "https://api.uniterouter.ai/v1",
        Some("UNITEROUTER_API_KEY"),
        128_000,
    ),
    t(
        "router-one",
        "Router One",
        "anthropic/claude-3-5-sonnet",
        "https://api.router.one/v1",
        Some("ROUTER_ONE_API_KEY"),
        128_000,
    ),
    t(
        "dedalus",
        "Dedalus",
        "anthropic/claude-3-5-sonnet",
        "https://api.dedaluslabs.ai/v1",
        Some("DEDALUS_API_KEY"),
        128_000,
    ),
    t(
        "tokenmix",
        "TokenMix",
        "gpt-4o",
        "https://api.tokenmix.ai/v1",
        Some("TOKENMIX_API_KEY"),
        128_000,
    ),
    t(
        "tokone",
        "TokOne",
        "gpt-4o",
        "https://api.tokone.ai/v1",
        Some("TOKONE_API_KEY"),
        128_000,
    ),
    t(
        "shuttleai",
        "ShuttleAI",
        "shuttleai/auto",
        "https://api.shuttleai.com/v1",
        Some("SHUTTLEAI_API_KEY"),
        128_000,
    ),
    t(
        "lambda",
        "Lambda",
        "meta-llama/Meta-Llama-3.1-70B-Instruct",
        "https://api.lambdalabs.com/v1",
        Some("LAMBDA_API_KEY"),
        128_000,
    ),
    t(
        "requesty",
        "Requesty",
        "openai/gpt-4o-mini",
        "https://router.requesty.ai/v1",
        Some("REQUESTY_API_KEY"),
        128_000,
    ),
    t(
        "portkey",
        "Portkey",
        "gpt-4o",
        "https://api.portkey.ai/v1",
        Some("PORTKEY_API_KEY"),
        128_000,
    ),
    t(
        "baseten",
        "Baseten",
        "deepseek-ai/DeepSeek-V4-Pro",
        "https://inference.baseten.co/v1",
        Some("BASETEN_API_KEY"),
        128_000,
    ),
    t(
        "arcee",
        "Arcee",
        "trinity-large-thinking",
        "https://api.arcee.ai/api/v1",
        Some("ARCEE_API_KEY"),
        128_000,
    ),
    t(
        "nebius",
        "Nebius",
        "meta-llama/Meta-Llama-3.1-70B-Instruct",
        "https://api.studio.nebius.ai/v1",
        Some("NEBIUS_API_KEY"),
        128_000,
    ),
    t(
        "inference",
        "Inference.net",
        "glm-5.2",
        "https://api.inference.net/v1",
        Some("INFERENCE_API_KEY"),
        128_000,
    ),
    t(
        "venice",
        "Venice",
        "zai-org-glm-5",
        "https://api.venice.ai/api/v1",
        Some("VENICE_API_KEY"),
        32_768,
    ),
    t(
        "glhf",
        "glhf",
        "hf:meta-llama/Llama-3.3-70B-Instruct",
        "https://glhf.chat/api/openai/v1",
        Some("GLHF_API_KEY"),
        128_000,
    ),
    t(
        "scaleway",
        "Scaleway",
        "llama-3.3-70b-instruct",
        "https://api.scaleway.ai/v1",
        Some("SCALEWAY_API_KEY"),
        128_000,
    ),
    t(
        "ovhcloud",
        "OVHcloud",
        "Llama-3.1-8B-Instruct",
        "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1",
        Some("OVHCLOUD_API_KEY"),
        32_768,
    ),
    t(
        "akashml",
        "AkashML",
        "zai-org/GLM-5.2",
        "https://api.akashml.com/v1",
        Some("AKASHML_API_KEY"),
        128_000,
    ),
    t(
        "inception",
        "Inception",
        "mercury-2",
        "https://api.inceptionlabs.ai/v1",
        Some("INCEPTION_API_KEY"),
        32_768,
    ),
    t(
        "morph",
        "Morph",
        "morph-v3-fast",
        "https://api.morphllm.com/v1",
        Some("MORPH_API_KEY"),
        128_000,
    ),
    t(
        "aionlabs",
        "Aion Labs",
        "aion-1.0-mini",
        "https://api.aionlabs.ai/v1",
        Some("AIONLABS_API_KEY"),
        128_000,
    ),
    t(
        "cortecs",
        "Cortecs",
        "gpt-4o",
        "https://api.cortecs.ai/v1",
        Some("CORTECS_API_KEY"),
        128_000,
    ),
    t(
        "ai302",
        "302.AI",
        "gpt-4o",
        "https://api.302.ai/v1",
        Some("AI302_API_KEY"),
        128_000,
    ),
    // Local model servers
    t(
        "jan",
        "Jan",
        "local-model",
        "http://localhost:1337/v1",
        None,
        128_000,
    ),
    t(
        "localai",
        "LocalAI",
        "local-model",
        "http://localhost:8080/v1",
        None,
        128_000,
    ),
    t(
        "llamafile",
        "llamafile",
        "local-model",
        "http://localhost:8080/v1",
        None,
        128_000,
    ),
    t(
        "text-generation-webui",
        "Text Generation WebUI",
        "local-model",
        "http://localhost:5000/v1",
        None,
        8_192,
    ),
    t(
        "koboldcpp",
        "KoboldCPP",
        "local-model",
        "http://localhost:5001/v1",
        None,
        8_192,
    ),
    t(
        "mistral-rs",
        "mistral.rs",
        "local-model",
        "http://localhost:1234/v1",
        None,
        128_000,
    ),
    t(
        "sglang",
        "SGLang",
        "local-model",
        "http://localhost:30000/v1",
        None,
        32_768,
    ),
    t(
        "mlc-llm",
        "MLC-LLM",
        "local-model",
        "http://localhost:8000/v1",
        None,
        32_768,
    ),
    t(
        "xinference",
        "Xinference",
        "local-model",
        "http://localhost:9997/v1",
        None,
        32_768,
    ),
    t(
        "aphrodite",
        "Aphrodite",
        "local-model",
        "http://localhost:2242/v1",
        None,
        128_000,
    ),
    t(
        "text-generation-inference",
        "Text Generation Inference",
        "local-model",
        "http://localhost:8080/v1",
        None,
        128_000,
    ),
    t(
        "lorax",
        "LoRAX",
        "local-model",
        "http://localhost:8080/v1",
        None,
        8_192,
    ),
    t(
        "litellm",
        "LiteLLM",
        "local-model",
        "http://localhost:4000/v1",
        None,
        128_000,
    ),
    // Common OpenCode-style endpoints
    t(
        "opencode",
        "OpenCode",
        "default",
        "http://localhost:3000/v1",
        None,
        128_000,
    ),
    ProviderTemplate {
        id: "codex",
        name: "OpenAI Codex",
        model: "codex-mini-latest",
        base_url: "https://api.openai.com/v1",
        env_key: Some("OPENAI_API_KEY"),
        extra_headers: None,
        context_window: Some(128_000),
        api_backend: Some("responses"),
    },
    ProviderTemplate {
        id: "claude-code",
        name: "Claude Code",
        model: "claude-3-5-sonnet-20241022",
        base_url: "https://api.anthropic.com/v1",
        env_key: Some("ANTHROPIC_API_KEY"),
        extra_headers: Some(&[("anthropic-version", "2023-06-01")]),
        context_window: Some(200_000),
        api_backend: Some("messages"),
    },
    t(
        "hermes",
        "Hermes",
        "Nous-Hermes-2-Yi-34B",
        "https://api.together.xyz/v1",
        Some("TOGETHER_API_KEY"),
        4_096,
    ),
    t(
        "omp",
        "OMP",
        "default",
        "http://localhost:5000/v1",
        Some("OMP_API_KEY"),
        8_192,
    ),
    // Anthropic / OpenRouter / xAI variants also in catalog for discoverability
    ProviderTemplate {
        id: "anthropic",
        name: "Anthropic",
        model: "claude-3-5-sonnet-20241022",
        base_url: "https://api.anthropic.com/v1",
        env_key: Some("ANTHROPIC_API_KEY"),
        extra_headers: Some(&[("anthropic-version", "2023-06-01")]),
        context_window: Some(200_000),
        api_backend: Some("messages"),
    },
    ProviderTemplate {
        id: "openrouter",
        name: "OpenRouter",
        model: "anthropic/claude-3.5-sonnet",
        base_url: "https://openrouter.ai/api/v1",
        env_key: Some("OPENROUTER_API_KEY"),
        extra_headers: Some(&[
            ("HTTP-Referer", "https://oh-my-grok.build"),
            ("X-Title", "oh-my-grok-build"),
        ]),
        context_window: Some(200_000),
        api_backend: Some("chat_completions"),
    },
    ProviderTemplate {
        id: "xai",
        name: "xAI",
        model: "grok-4.5",
        base_url: "https://api.x.ai/v1",
        env_key: Some("XAI_API_KEY"),
        extra_headers: None,
        context_window: Some(500_000),
        api_backend: Some("chat_completions"),
    },
    ProviderTemplate {
        id: "openai",
        name: "OpenAI",
        model: "gpt-4o",
        base_url: "https://api.openai.com/v1",
        env_key: Some("OPENAI_API_KEY"),
        extra_headers: None,
        context_window: Some(128_000),
        api_backend: Some("chat_completions"),
    },
    ProviderTemplate {
        id: "ollama",
        name: "Ollama (local)",
        model: "codellama",
        base_url: "http://localhost:11434/v1",
        env_key: None,
        extra_headers: None,
        context_window: Some(128_000),
        api_backend: Some("chat_completions"),
    },
    ProviderTemplate {
        id: "lmstudio",
        name: "LM Studio (local)",
        model: "local-model",
        base_url: "http://localhost:1234/v1",
        env_key: Some("LMSTUDIO_API_KEY"),
        extra_headers: None,
        context_window: Some(128_000),
        api_backend: Some("chat_completions"),
    },
    ProviderTemplate {
        id: "vllm",
        name: "vLLM",
        model: "local-model",
        base_url: "http://localhost:8000/v1",
        env_key: Some("OMGB_VLLM_API_KEY"),
        extra_headers: None,
        context_window: Some(128_000),
        api_backend: Some("chat_completions"),
    },
    ProviderTemplate {
        id: "llama-cpp",
        name: "llama.cpp server",
        model: "local-model",
        base_url: "http://localhost:8080/v1",
        env_key: Some("OMGB_LLAMA_CPP_API_KEY"),
        extra_headers: None,
        context_window: Some(128_000),
        api_backend: Some("chat_completions"),
    },
    ProviderTemplate {
        id: "tabby",
        name: "TabbyAPI",
        model: "local-model",
        base_url: "http://localhost:5000/v1",
        env_key: Some("OMGB_TABBY_API_KEY"),
        extra_headers: None,
        context_window: Some(128_000),
        api_backend: Some("chat_completions"),
    },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_has_at_least_100_entries() {
        assert!(
            TEMPLATES.len() >= 100,
            "catalog has {} entries",
            TEMPLATES.len()
        );
    }

    #[test]
    fn catalog_contains_expected_providers() {
        for id in &[
            "openai",
            "anthropic",
            "xai",
            "openrouter",
            "groq",
            "gemini",
            "deepseek",
            "ollama",
            "lmstudio",
            "vllm",
            "llama-cpp",
            "tabby",
            "jan",
            "opencode",
            "codex",
            "claude-code",
            "uniterouter",
            "router-one",
            "dedalus",
            "tokenmix",
            "tokone",
            "sglang",
        ] {
            assert!(
                provider_template(id).is_some(),
                "expected provider {id} missing from catalog"
            );
        }
    }

    #[test]
    fn catalog_unknown_returns_none() {
        assert!(provider_template("not-a-real-provider").is_none());
    }

    #[test]
    fn catalog_config_fields_are_populated() {
        let p = provider_template("groq").unwrap();
        assert_eq!(p.id, "groq");
        assert_eq!(p.name, "Groq");
        assert_eq!(p.model, "llama-3.3-70b-versatile");
        assert!(p.base_url.contains("groq.com"));
        assert!(p.context_window.is_some());
        assert_eq!(p.api_backend.as_deref(), Some("chat_completions"));
    }

    #[test]
    fn catalog_local_provider_has_no_canonical_env_key() {
        let p = provider_template("jan").unwrap();
        let keys = p.env_key.expect("env_key should be set");
        assert!(keys.iter().any(|k| k.starts_with("OMGB_")));
        assert!(!keys.iter().any(|k| k == "JAN_API_KEY"));
    }
}
