//! Expanded provider catalog for `omgb provider add <id>`.
//!
//! Contains 100+ OpenAI-compatible cloud endpoints, local model servers, and
//! common OpenCode-style endpoint templates.

use super::{ProviderConfig, provider_env_keys};

const fn t(
    id: &'static str,
    name: &'static str,
    model: &'static str,
    base_url: &'static str,
    env_key: Option<&'static str>,
    context_window: u64,
) -> ProviderTemplate {
    ProviderTemplate {
        id,
        name,
        model,
        base_url,
        env_key,
        context_window: Some(context_window),
        api_backend: Some("chat_completions"),
    }
}

#[derive(Debug, Clone)]
pub struct ProviderTemplate {
    pub id: &'static str,
    pub name: &'static str,
    pub model: &'static str,
    pub base_url: &'static str,
    pub env_key: Option<&'static str>,
    pub context_window: Option<u64>,
    pub api_backend: Option<&'static str>,
}

impl ProviderTemplate {
    pub fn to_provider_config(&self) -> ProviderConfig {
        ProviderConfig {
            id: self.id.into(),
            name: self.name.into(),
            model: self.model.into(),
            base_url: self.base_url.into(),
            api_backend: self.api_backend.map(|s| s.into()),
            env_key: provider_env_keys(self.id, self.env_key),
            extra_headers: None,
            context_window: self.context_window,
            auto_compact_threshold_percent: Some(80),
            temperature: None,
            top_p: None,
            max_completion_tokens: None,
        }
    }
}

pub fn provider_template(id: &str) -> Option<ProviderConfig> {
    TEMPLATES
        .iter()
        .find(|t| t.id == id)
        .map(|t| t.to_provider_config())
}

pub(crate) const TEMPLATES: &[ProviderTemplate] = &[
    // OpenAI-compatible cloud endpoints
    t(
        "groq",
        "Groq",
        "llama-3.3-70b-versatile",
        "https://api.groq.com/openai/v1",
        Some("GROQ_API_KEY"),
        128_000,
    ),
    t(
        "mistral",
        "Mistral",
        "mistral-large-latest",
        "https://api.mistral.ai/v1",
        Some("MISTRAL_API_KEY"),
        128_000,
    ),
    t(
        "cohere",
        "Cohere",
        "command-r-plus",
        "https://api.cohere.com/v1",
        Some("COHERE_API_KEY"),
        128_000,
    ),
    t(
        "together",
        "Together AI",
        "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        "https://api.together.xyz/v1",
        Some("TOGETHER_API_KEY"),
        128_000,
    ),
    t(
        "fireworks",
        "Fireworks AI",
        "accounts/fireworks/models/llama-v3p1-70b-instruct",
        "https://api.fireworks.ai/inference/v1",
        Some("FIREWORKS_API_KEY"),
        128_000,
    ),
    t(
        "perplexity",
        "Perplexity",
        "sonar",
        "https://api.perplexity.ai",
        Some("PERPLEXITY_API_KEY"),
        128_000,
    ),
    t(
        "deepseek",
        "DeepSeek",
        "deepseek-chat",
        "https://api.deepseek.com/v1",
        Some("DEEPSEEK_API_KEY"),
        128_000,
    ),
    t(
        "ai21",
        "AI21",
        "jamba-1.5-mini",
        "https://api.ai21.com/studio/v1",
        Some("AI21_API_KEY"),
        256_000,
    ),
    t(
        "gemini",
        "Gemini",
        "gemini-1.5-flash",
        "https://generativelanguage.googleapis.com/v1beta/openai",
        Some("GEMINI_API_KEY"),
        128_000,
    ),
    t(
        "anyscale",
        "Anyscale",
        "meta-llama/Llama-2-70b-chat-hf",
        "https://api.endpoints.anyscale.com/v1",
        Some("ANYSCALE_API_KEY"),
        4_096,
    ),
    t(
        "cerebras",
        "Cerebras",
        "llama3.1-70b",
        "https://api.cerebras.net/v1",
        Some("CEREBRAS_API_KEY"),
        128_000,
    ),
    t(
        "friendli",
        "FriendliAI",
        "meta-llama-3.1-70b-instruct",
        "https://api.friendli.ai/v1",
        Some("FRIENDLI_API_KEY"),
        128_000,
    ),
    t(
        "hyperbolic",
        "Hyperbolic",
        "meta-llama/Meta-Llama-3.1-70B-Instruct",
        "https://api.hyperbolic.xyz/v1",
        Some("HYPERBOLIC_API_KEY"),
        8_192,
    ),
    t(
        "lamini",
        "Lamini",
        "Llama-3.1-8B-Instruct",
        "https://api.lamini.ai/v1",
        Some("LAMINI_API_KEY"),
        8_192,
    ),
    t(
        "monster",
        "Monster API",
        "llama3-70b",
        "https://api.monsterapi.ai/v1",
        Some("MONSTER_API_KEY"),
        8_192,
    ),
    t(
        "novita",
        "Novita",
        "meta-llama/llama-3.3-70b-instruct",
        "https://api.novita.ai/v3/openai",
        Some("NOVITA_API_KEY"),
        128_000,
    ),
    t(
        "octoai",
        "OctoAI",
        "meta-llama-3-70b-instruct",
        "https://api.octoai.cloud/v1",
        Some("OCTOAI_API_KEY"),
        4_096,
    ),
    t(
        "predibase",
        "Predibase",
        "llama-3.1-8b",
        "https://serving.predibase.com/v1",
        Some("PREDIBASE_API_KEY"),
        8_192,
    ),
    t(
        "replicate",
        "Replicate",
        "meta/llama-2-70b-chat",
        "https://api.replicate.com/v1",
        Some("REPLICATE_API_KEY"),
        4_096,
    ),
    t(
        "upstage",
        "Upstage",
        "solar-pro",
        "https://api.upstage.ai/v1/solar",
        Some("UPSTAGE_API_KEY"),
        32_768,
    ),
    t(
        "writer",
        "Writer",
        "palmyra-x-004",
        "https://api.writer.com/v1",
        Some("WRITER_API_KEY"),
        128_000,
    ),
    t(
        "zhipu",
        "Zhipu AI",
        "glm-4",
        "https://open.bigmodel.cn/api/paas/v4",
        Some("ZHIPU_API_KEY"),
        128_000,
    ),
    t(
        "moonshot",
        "Moonshot",
        "moonshot-v1-8k",
        "https://api.moonshot.cn/v1",
        Some("MOONSHOT_API_KEY"),
        8_192,
    ),
    t(
        "qwen",
        "Qwen",
        "qwen-plus",
        "https://dashscope.aliyuncs.com/compatible-mode/v1",
        Some("QWEN_API_KEY"),
        128_000,
    ),
    t(
        "yi",
        "01.AI",
        "yi-large",
        "https://api.01.ai/v1",
        Some("YI_API_KEY"),
        16_384,
    ),
    t(
        "lingyi",
        "Lingyi Wanwu",
        "abab6.5-chat",
        "https://api.lingyiwanwu.com/v1",
        Some("LINGYI_API_KEY"),
        8_192,
    ),
    t(
        "minimax",
        "MiniMax",
        "abab5.5-chat",
        "https://api.minimaxi.chat/v1",
        Some("MINIMAX_API_KEY"),
        8_192,
    ),
    t(
        "baichuan",
        "Baichuan",
        "Baichuan4",
        "https://api.baichuan-ai.com/v1",
        Some("BAICHUAN_API_KEY"),
        128_000,
    ),
    t(
        "spark",
        "Spark",
        "generalv3.5",
        "https://spark-api-open.xf-yun.com/v1",
        Some("SPARK_API_KEY"),
        8_192,
    ),
    t(
        "doubao",
        "Doubao",
        "doubao-pro-32k",
        "https://ark.cn-beijing.volces.com/api/v3",
        Some("DOUBAO_API_KEY"),
        32_768,
    ),
    t(
        "hunyuan",
        "Hunyuan",
        "hunyuan-pro",
        "https://hunyuan-api.tencent.com/v1",
        Some("HUNYUAN_API_KEY"),
        32_768,
    ),
    t(
        "stepfun",
        "Stepfun",
        "step-1-8k",
        "https://api.stepfun.com/v1",
        Some("STEPFUN_API_KEY"),
        8_192,
    ),
    t(
        "internlm",
        "InternLM",
        "internlm2.5-20b",
        "https://api.intern-ai.org.cn/v1",
        Some("INTERNLM_API_KEY"),
        32_768,
    ),
    t(
        "sensenova",
        "SenseNova",
        "SenseChat-5",
        "https://api.sensenova.cn/v1",
        Some("SENSENOVA_API_KEY"),
        32_768,
    ),
    t(
        "github-models",
        "GitHub Models",
        "gpt-4o",
        "https://models.inference.ai.azure.com",
        Some("GITHUB_MODELS_API_KEY"),
        128_000,
    ),
    t(
        "siliconflow",
        "SiliconFlow",
        "Qwen/Qwen2.5-72B-Instruct",
        "https://api.siliconflow.cn/v1",
        Some("SILICONFLOW_API_KEY"),
        128_000,
    ),
    t(
        "sambanova",
        "SambaNova",
        "Meta-Llama-3.1-70B-Instruct",
        "https://api.sambanova.ai/v1",
        Some("SAMBANOVA_API_KEY"),
        128_000,
    ),
    t(
        "lepton",
        "Lepton",
        "llama3-1-70b",
        "https://api.lepton.ai/v1",
        Some("LEPTON_API_KEY"),
        128_000,
    ),
    t(
        "nvidia",
        "NVIDIA NIM",
        "nvidia/llama-3.1-nemotron-70b-instruct",
        "https://integrate.api.nvidia.com/v1",
        Some("NVIDIA_API_KEY"),
        128_000,
    ),
    t(
        "deepinfra",
        "DeepInfra",
        "deepseek-ai/DeepSeek-V3",
        "https://api.deepinfra.com/v1/openai",
        Some("DEEPINFRA_API_KEY"),
        128_000,
    ),
    t(
        "aimlapi",
        "AIMLAPI",
        "gpt-4o",
        "https://api.aimlapi.com/v1",
        Some("AIMLAPI_API_KEY"),
        128_000,
    ),
    t(
        "arliai",
        "ArliAI",
        "Llama-3.3-70B-ArliAI-RPMax-v3",
        "https://api.arliai.com/v1",
        Some("ARLIAI_API_KEY"),
        128_000,
    ),
    t(
        "chutes",
        "Chutes",
        "Qwen/Qwen3-32B-TEE",
        "https://llm.chutes.ai/v1",
        Some("CHUTES_API_KEY"),
        128_000,
    ),
    t(
        "kluster",
        "Kluster",
        "meta-llama/Llama-3.1-405B-Instruct",
        "https://api.kluster.ai/v1",
        Some("KLUSTER_API_KEY"),
        128_000,
    ),
    t(
        "speka",
        "Speka",
        "meta/llama-3.3-70b-instruct",
        "https://speka.me/v1",
        Some("SPEKA_API_KEY"),
        128_000,
    ),
    t(
        "featherless",
        "Featherless",
        "Qwen/Qwen2.5-7B-Instruct",
        "https://api.featherless.ai/v1",
        Some("FEATHERLESS_API_KEY"),
        128_000,
    ),
    t(
        "aipower",
        "AIPower",
        "deepseek/deepseek-chat",
        "https://api.aipower.me/v1",
        Some("AIPOWER_API_KEY"),
        128_000,
    ),
    t(
        "banana",
        "Banana",
        "llama-2-70b",
        "https://api.banana.dev/v1",
        Some("BANANA_API_KEY"),
        4_096,
    ),
    t(
        "huggingface",
        "Hugging Face",
        "meta-llama/Llama-3.1-70B-Instruct",
        "https://api-inference.huggingface.co/v1",
        Some("HUGGINGFACE_API_KEY"),
        4_096,
    ),
    t(
        "gradient",
        "Gradient",
        "llama2-70b",
        "https://api.gradient.ai/v1",
        Some("GRADIENT_API_KEY"),
        4_096,
    ),
    t(
        "gooseai",
        "GooseAI",
        "gpt-neo-20b",
        "https://api.goose.ai/v1",
        Some("GOOSEAI_API_KEY"),
        2_048,
    ),
    t(
        "infermatic",
        "Infermatic",
        "migt-7b",
        "https://api.infermatic.ai/v1",
        Some("INFERMATIC_API_KEY"),
        8_192,
    ),
    t(
        "leaf",
        "Leaf",
        "llama-3.1-8b",
        "https://api.getleaf.ai/v1",
        Some("LEAF_API_KEY"),
        4_096,
    ),
    t(
        "mystic",
        "Mystic",
        "llama-3.1-70b",
        "https://api.mystic.ai/v1",
        Some("MYSTIC_API_KEY"),
        8_192,
    ),
    t(
        "petals",
        "Petals",
        "meta-llama/Llama-2-70b-chat-hf",
        "https://api.petals.dev/v1",
        Some("PETALS_API_KEY"),
        4_096,
    ),
    t(
        "pipeline",
        "Pipeline",
        "llama3-70b",
        "https://api.pipeline.ai/v2",
        Some("PIPELINE_API_KEY"),
        8_192,
    ),
    t(
        "sail",
        "Sail",
        "sail-7b",
        "https://api.sail.ai/v1",
        Some("SAIL_API_KEY"),
        4_096,
    ),
    t(
        "salute",
        "Salute",
        "Salute-7B",
        "https://api.salute.ai/v1",
        Some("SALUTE_API_KEY"),
        4_096,
    ),
    t(
        "spell",
        "Spell",
        "gpt-4o",
        "https://api.spell.ml/v1",
        Some("SPELL_API_KEY"),
        8_192,
    ),
    t(
        "textcortex",
        "TextCortex",
        "chat-gpt",
        "https://api.textcortex.com/v1",
        Some("TEXTCORTEX_API_KEY"),
        8_192,
    ),
    t(
        "thebai",
        "TheB.AI",
        "gpt-4o",
        "https://api.theb.ai/v1",
        Some("THEBAI_API_KEY"),
        8_192,
    ),
    t(
        "twelve-labs",
        "Twelve Labs",
        "pegasus-1",
        "https://api.twelvelabs.io/v1",
        Some("TWELVE_LABS_API_KEY"),
        8_192,
    ),
    t(
        "turbine",
        "Turbine",
        "llama-3.1-70b",
        "https://api.turbine.ai/v1",
        Some("TURBINE_API_KEY"),
        8_192,
    ),
    t(
        "tune",
        "Tune",
        "llama-3.1-8b",
        "https://api.tune.app/v1",
        Some("TUNE_API_KEY"),
        8_192,
    ),
    t(
        "wavescape",
        "Wavescape",
        "llama-3",
        "https://api.wavescape.io/v1",
        Some("WAVESCAPE_API_KEY"),
        4_096,
    ),
    t(
        "poe",
        "Poe",
        "claude-3-sonnet",
        "https://api.poe.com/v1",
        Some("POE_API_KEY"),
        128_000,
    ),
    t(
        "amazon-bedrock",
        "Amazon Bedrock",
        "anthropic.claude-3-5-sonnet",
        "https://bedrock-runtime.us-east-1.amazonaws.com",
        Some("BEDROCK_API_KEY"),
        200_000,
    ),
    // Local model servers
    t(
        "jan",
        "Jan",
        "local-model",
        "http://localhost:1337/v1",
        None,
        128_000,
    ),
    t(
        "localai",
        "LocalAI",
        "local-model",
        "http://localhost:8080/v1",
        None,
        128_000,
    ),
    t(
        "llamafile",
        "llamafile",
        "local-model",
        "http://localhost:8080/v1",
        None,
        128_000,
    ),
    t(
        "text-generation-webui",
        "Text Generation WebUI",
        "local-model",
        "http://localhost:5000/v1",
        None,
        8_192,
    ),
    t(
        "koboldcpp",
        "KoboldCPP",
        "local-model",
        "http://localhost:5001/api/v1",
        None,
        8_192,
    ),
    t(
        "mistral-rs",
        "mistral.rs",
        "local-model",
        "http://localhost:1234/v1",
        None,
        128_000,
    ),
    t(
        "sglang",
        "SGLang",
        "local-model",
        "http://localhost:30000/v1",
        None,
        32_768,
    ),
    t(
        "tensorrt-llm",
        "TensorRT-LLM",
        "local-model",
        "http://localhost:8000/v1",
        None,
        128_000,
    ),
    t(
        "mlc-llm",
        "MLC-LLM",
        "local-model",
        "http://localhost:8000/v1",
        None,
        32_768,
    ),
    t(
        "xinference",
        "Xinference",
        "local-model",
        "http://localhost:9997/v1",
        None,
        32_768,
    ),
    t(
        "faraday",
        "Faraday",
        "local-model",
        "http://localhost:8080/v1",
        None,
        8_192,
    ),
    t(
        "aichat",
        "AiChat",
        "local-model",
        "http://localhost:8080/v1",
        None,
        8_192,
    ),
    t(
        "ava",
        "Ava",
        "local-model",
        "http://localhost:8000/v1",
        None,
        8_192,
    ),
    t(
        "exllamav2",
        "ExLlamaV2",
        "local-model",
        "http://localhost:5000/v1",
        None,
        8_192,
    ),
    t(
        "ctranslate2",
        "CTranslate2",
        "local-model",
        "http://localhost:8080/v1",
        None,
        8_192,
    ),
    t(
        "ctransformers",
        "ctransformers",
        "local-model",
        "http://localhost:8080/v1",
        None,
        4_096,
    ),
    t(
        "candle",
        "Candle",
        "local-model",
        "http://localhost:8080/v1",
        None,
        4_096,
    ),
    t(
        "triton",
        "Triton",
        "local-model",
        "http://localhost:8000/v2/models/ensemble/generate",
        None,
        128_000,
    ),
    t(
        "text-generation-inference",
        "Text Generation Inference",
        "local-model",
        "http://localhost:8080/v1",
        None,
        128_000,
    ),
    t(
        "lorax",
        "LoRAX",
        "local-model",
        "http://localhost:8080/v1",
        None,
        8_192,
    ),
    // Common OpenCode-style endpoints
    t(
        "opencode",
        "OpenCode",
        "default",
        "http://localhost:3000/v1",
        None,
        128_000,
    ),
    t(
        "codex",
        "OpenAI Codex",
        "codex",
        "https://api.openai.com/v1",
        Some("OPENAI_API_KEY"),
        128_000,
    ),
    ProviderTemplate {
        id: "claude-code",
        name: "Claude Code",
        model: "claude-3-5-sonnet-20241022",
        base_url: "https://api.anthropic.com/v1",
        env_key: Some("ANTHROPIC_API_KEY"),
        context_window: Some(200_000),
        api_backend: Some("messages"),
    },
    t(
        "hermes",
        "Hermes",
        "Nous-Hermes-2-Yi-34B",
        "https://api.together.xyz/v1",
        Some("TOGETHER_API_KEY"),
        4_096,
    ),
    t(
        "pi",
        "Pi",
        "pi",
        "https://api.inflection.ai/v1",
        Some("PI_API_KEY"),
        8_192,
    ),
    t(
        "omp",
        "OMP",
        "default",
        "http://localhost:5000/v1",
        Some("OMP_API_KEY"),
        8_192,
    ),
    // Anthropic / OpenRouter / xAI variants also in catalog for discoverability
    ProviderTemplate {
        id: "anthropic",
        name: "Anthropic",
        model: "claude-3-5-sonnet-20241022",
        base_url: "https://api.anthropic.com/v1",
        env_key: Some("ANTHROPIC_API_KEY"),
        context_window: Some(200_000),
        api_backend: Some("messages"),
    },
    ProviderTemplate {
        id: "openrouter",
        name: "OpenRouter",
        model: "anthropic/claude-3.5-sonnet",
        base_url: "https://openrouter.ai/api/v1",
        env_key: Some("OPENROUTER_API_KEY"),
        context_window: Some(200_000),
        api_backend: Some("chat_completions"),
    },
    ProviderTemplate {
        id: "xai",
        name: "xAI",
        model: "grok-4.5",
        base_url: "https://api.x.ai/v1",
        env_key: Some("XAI_API_KEY"),
        context_window: Some(500_000),
        api_backend: Some("chat_completions"),
    },
    ProviderTemplate {
        id: "openai",
        name: "OpenAI",
        model: "gpt-4o",
        base_url: "https://api.openai.com/v1",
        env_key: Some("OPENAI_API_KEY"),
        context_window: Some(128_000),
        api_backend: Some("chat_completions"),
    },
    ProviderTemplate {
        id: "ollama",
        name: "Ollama (local)",
        model: "codellama",
        base_url: "http://localhost:11434/v1",
        env_key: None,
        context_window: Some(128_000),
        api_backend: Some("chat_completions"),
    },
    ProviderTemplate {
        id: "lmstudio",
        name: "LM Studio (local)",
        model: "local-model",
        base_url: "http://localhost:1234/v1",
        env_key: Some("LMSTUDIO_API_KEY"),
        context_window: Some(128_000),
        api_backend: Some("chat_completions"),
    },
    ProviderTemplate {
        id: "vllm",
        name: "vLLM",
        model: "local-model",
        base_url: "http://localhost:8000/v1",
        env_key: Some("OMGB_VLLM_API_KEY"),
        context_window: Some(128_000),
        api_backend: Some("chat_completions"),
    },
    ProviderTemplate {
        id: "llama-cpp",
        name: "llama.cpp server",
        model: "local-model",
        base_url: "http://localhost:8080/v1",
        env_key: Some("OMGB_LLAMA_CPP_API_KEY"),
        context_window: Some(128_000),
        api_backend: Some("chat_completions"),
    },
    ProviderTemplate {
        id: "tabby",
        name: "TabbyAPI",
        model: "local-model",
        base_url: "http://localhost:5000/v1",
        env_key: Some("OMGB_TABBY_API_KEY"),
        context_window: Some(128_000),
        api_backend: Some("chat_completions"),
    },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_has_at_least_100_entries() {
        assert!(
            TEMPLATES.len() >= 100,
            "catalog has {} entries",
            TEMPLATES.len()
        );
    }

    #[test]
    fn catalog_contains_expected_providers() {
        for id in &[
            "openai",
            "anthropic",
            "xai",
            "openrouter",
            "groq",
            "gemini",
            "deepseek",
            "ollama",
            "lmstudio",
            "vllm",
            "llama-cpp",
            "tabby",
            "jan",
            "opencode",
            "codex",
            "claude-code",
        ] {
            assert!(
                provider_template(id).is_some(),
                "expected provider {id} missing from catalog"
            );
        }
    }

    #[test]
    fn catalog_unknown_returns_none() {
        assert!(provider_template("not-a-real-provider").is_none());
    }

    #[test]
    fn catalog_config_fields_are_populated() {
        let p = provider_template("groq").unwrap();
        assert_eq!(p.id, "groq");
        assert_eq!(p.name, "Groq");
        assert_eq!(p.model, "llama-3.3-70b-versatile");
        assert!(p.base_url.contains("groq.com"));
        assert!(p.context_window.is_some());
        assert_eq!(p.api_backend.as_deref(), Some("chat_completions"));
    }

    #[test]
    fn catalog_local_provider_has_no_canonical_env_key() {
        let p = provider_template("jan").unwrap();
        let keys = p.env_key.expect("env_key should be set");
        assert!(keys.iter().any(|k| k.starts_with("OMGB_")));
        assert!(!keys.iter().any(|k| k == "JAN_API_KEY"));
    }
}
